import Head from "next/head";
import '../styles/Home.module.css'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faUsersRectangle,
  faSquareEnvelope,
  faCalendar,
  faMapSigns,
  faSquarePhoneFlip,
  faLock
} from "@fortawesome/free-solid-svg-icons";
import { useState } from "react";
import axios from 'axios';

export default function Home() {

  const [listCard, setListCard] = useState([{'name':'defitra','image':'https://mdbcdn.b-cdn.net/img/new/avatars/2.webp'}]);
  const [value, setValue] = useState('');

  const addCard = () => {
    setListCard([...listCard, {'name':value,'image':'https://mdbcdn.b-cdn.net/img/new/avatars/2.webp'}])
  }
  const clearAllCard = () => {
    setListCard([])
  }
  const autoGenerate = () => {
    axios.get(`https://randomuser.me/api`)
      .then(res => {
        const person = res;
        setListCard([...listCard, {'name':person.data.results[0].name.first + ' '+ person.data.results[0].name.last,'image':person.data.results[0].picture.medium}])
      })
  }
  
  return (
    <main className="container">
      <Head>
        <title>Test Front End - PT Telkom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="col-lg-6 offset-lg-3">
        <h4 class="mt-5">Personal information</h4>
        <p>This Information Will be Displayed publicly so be careful what you share</p>

        <form>
          <div class="form-group">
            <label for="full_name">Full Name</label>
            <input type="text" class="form-control" id="full_name" placeholder="Your Name" onChange={e => { setValue(e.currentTarget.value); }} maxLength={50}/>
          </div>
          <br />
          <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" class="form-control" id="email" placeholder="yourmail@gmail.com" />
          </div>
          <br />
          <div class="form-group">
            <label for="date_of_birth">Date Of Birth</label>
            <input type="date" class="form-control" id="date_of_birth" placeholder="dd/mm/yy" />
          </div>
          <br />
          <div class="form-group">
            <label for="address">Address</label>
            <input type="text" class="form-control" id="address" placeholder="Street Address" maxLength={255}/>
          </div>
          <br />
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" placeholder="***************" minLength={6}/>
          </div>

          <br />
          <div>
            <button type="submit" class="btn btn-secondary">Cancel</button>
            &nbsp;
            &nbsp;
            <button type="button" class="btn btn-primary" onClick={addCard}>Submit</button>
            <button type="button" class="btn btn-success" style={{ 'float': 'right' }} onClick={autoGenerate}>Auto Generated</button>
          </div>

        </form>
      </div>
      <br /><br />
      <div style={{ 'width': '100%', 'height': '15px', 'borderBottom': '1px solid grey', 'textAlign': 'center' }}>
        <button style={{
          'fontSize': '15px', 'backgroundColor': 'white', 'padding': '0 10px', 'color': 'red', 'backgroundRepeat': 'no-repeat',
          'border': 'none',
          'cursor': 'pointer',
          'overflow': 'hidden',
          'outline': 'none'
        }} onClick={clearAllCard}>
          Clear All List User
        </button>
      </div>
      <br /><br />
      <div class="row row-cols-1 row-cols-md-3 g-4">
        {listCard.map((val) => (
          <div class="col">
            <div class="card h-100">
              <div class="text-center">
                <img 
                src={val.image} 
                class="card-img-top rounded-circle img-thumbnail" alt="..." style={{ 'width': '200px' }} />
              </div>
              <div class="card-body">
                <p class="card-text text-center">Hi, My Name Is</p>
                <h5 class="card-title text-center">{val.name}</h5>
              </div>
              <div class="card-footer">
                <div className="row">
                  <div className="col-md-2">
                    <FontAwesomeIcon
                      icon={faUsersRectangle}
                      style={{ fontSize: 15, color: "red" }}
                    />
                  </div>
                  <div className="col-md-2">
                    <FontAwesomeIcon
                      icon={faSquareEnvelope}
                      style={{ fontSize: 15, color: "red" }}

                    />
                  </div>
                  <div className="col-md-2">
                    <FontAwesomeIcon
                      icon={faCalendar}
                      style={{ fontSize: 15, color: "red" }}
                    />
                  </div>
                  <div className="col-md-2">
                    <FontAwesomeIcon
                      icon={faMapSigns}
                      style={{ fontSize: 15, color: "red" }}
                    />
                  </div>
                  <div className="col-md-2">
                    <FontAwesomeIcon
                      icon={faSquarePhoneFlip}
                      style={{ fontSize: 15, color: "red" }}
                    />
                  </div>
                  <div className="col-md-2">
                    <FontAwesomeIcon
                      icon={faLock}
                      style={{ fontSize: 15, color: "red" }}
                    />
                  </div>
                </div>

              </div>
            </div>
            <br />
          </div>
        ))}
      </div>
    </main>
  );
}